FROM oven/bun:1.4.2 AS build

WORKDIR /app
ENV DATABASE_URL=mysql://petmatch:petmatch-local@mysql:3306/petmatch_web
ENV BUN_CONFIG_SKIP_SAVE_LOCKFILE=true
ENV NEXT_TELEMETRY_DISABLED=1

COPY package.json package-lock.json ./
RUN bun install --no-save

COPY . .
RUN bunx --bun prisma generate && bun --bun run build

FROM build AS migrator
CMD ["bunx", "--bun", "prisma", "migrate", "deploy"]

FROM build AS production
RUN bun install --no-save --production

FROM oven/bun:1.4.2 AS runtime
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000

COPY --from=production --chown=bun:bun /app/ ./
USER bun
CMD ["bun", "--bun", "run", "start"]
