# Generated by Django 5.0.14 on 2026-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Inviata'), ('IN_REVIEW', 'In Valutazione dal Rifugio'), ('HOME_VISIT', 'Visita Pre-Affido Programmata'), ('APPROVED', 'Approvata'), ('REJECTED', 'Rifiutata'), ('WITHDRAWN', "Ritirata dall'Utente")], default='SUBMITTED', max_length=20, verbose_name='Stato Candidatura')),
                ('motivational_notes', models.TextField(verbose_name='Lettera Motivazionale')),
                ('compatibility_score_at_submission', models.FloatField(default=0.0, verbose_name="Punteggio Compatibilità ML all'Invio")),
                ('shelter_notes', models.TextField(blank=True, verbose_name='Note Interne del Rifugio')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Invio Candidatura')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Ultimo Aggiornamento')),
            ],
            options={
                'verbose_name': 'Domanda di Adozione',
                'verbose_name_plural': 'Domande di Adozione',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Animale')),
                ('species', models.CharField(choices=[('DOG', 'Cane'), ('CAT', 'Gatto'), ('OTHER', 'Altro')], default='DOG', max_length=10, verbose_name='Specie')),
                ('age_years', models.PositiveIntegerField(default=0, verbose_name='Età (Anni)')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='Età (Mesi)')),
                ('gender', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=10, verbose_name='Sesso')),
                ('size', models.CharField(choices=[('SMALL', 'Piccola (fino a 10kg)'), ('MEDIUM', 'Media (10-25kg)'), ('LARGE', 'Grande (25-45kg)'), ('GIANT', 'Gigante (oltre 45kg)')], default='MEDIUM', max_length=10, verbose_name='Taglia')),
                ('energy_level', models.CharField(choices=[('LOW', 'Basso (Tranquillo / Anziano)'), ('MEDIUM', 'Medio (Passeggiate regolari)'), ('HIGH', 'Alto (Molto energico)'), ('VERY_HIGH', 'Molto Alto (Lavoro / Sport)')], default='MEDIUM', max_length=15, verbose_name='Livello Energia')),
                ('good_with_cats', models.BooleanField(blank=True, null=True, verbose_name='Compatibile con Gatti')),
                ('good_with_dogs', models.BooleanField(blank=True, null=True, verbose_name='Compatibile con Cani')),
                ('good_with_children', models.BooleanField(blank=True, null=True, verbose_name='Compatibile con Bambini')),
                ('requires_garden', models.BooleanField(default=False, verbose_name='Giardino Obbligatorio')),
                ('max_hours_alone_per_day', models.PositiveIntegerField(default=6, verbose_name='Ore Max Solitudine al Giorno')),
                ('required_experience_level', models.CharField(choices=[('BEGINNER', 'Prima esperienza'), ('INTERMEDIATE', 'Esperienza intermedia'), ('EXPERT', 'Esperto / Educatore Cinofilo')], default='BEGINNER', max_length=20, verbose_name='Livello Esperienza Richiesto Adottante')),
                ('is_spayed_neutered', models.BooleanField(default=False, verbose_name='Sterilizzato / Castrato')),
                ('is_vaccinated', models.BooleanField(default=False, verbose_name='Vaccinato')),
                ('is_microchipped', models.BooleanField(default=True, verbose_name='Microchippato')),
                ('microchip_code', models.CharField(blank=True, max_length=50, verbose_name='Codice Microchip')),
                ('special_needs', models.BooleanField(default=False, verbose_name='Bisogni Speciali / Cure Continuative')),
                ('health_notes', models.TextField(blank=True, verbose_name='Note Cliniche / Sanitarie')),
                ('description', models.TextField(verbose_name='Descrizione e Carattere')),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('AVAILABLE', 'Disponibile per adozione'), ('PENDING', 'Richiesta in corso'), ('ADOPTED', 'Adottato'), ('CARE', 'In cure mediche / Stallo'), ('ARCHIVED', 'Archiviato')], default='DRAFT', max_length=15, verbose_name='Stato Adozione')),
                ('date_entry_shelter', models.DateField(verbose_name='Data Ingresso in Rifugio')),
                ('date_adopted', models.DateField(blank=True, null=True, verbose_name='Data Adozione')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione Scheda')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Ultima Modifica')),
            ],
            options={
                'verbose_name': 'Animale',
                'verbose_name_plural': 'Animali',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/', verbose_name='File Immagine')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Didascalia')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Foto Copertina')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine Ordinamento')),
            ],
            options={
                'verbose_name': 'Immagine Animale',
                'verbose_name_plural': 'Immagini Animali',
                'ordering': ['order', '-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('DOG', 'Cane'), ('CAT', 'Gatto'), ('OTHER', 'Altro')], default='DOG', max_length=10, verbose_name='Specie')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Razza')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione Razza')),
            ],
            options={
                'verbose_name': 'Razza',
                'verbose_name_plural': 'Razze',
                'ordering': ['species', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator_name', models.CharField(max_length=150, verbose_name='Nome Volontario / Operatore')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data Programmata Visita')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Effettiva Esecuzione')),
                ('outcome', models.CharField(choices=[('PENDING', 'In Attesa'), ('PASSED', 'Esito Positivo'), ('FAILED', 'Esito Negativo')], default='PENDING', max_length=15, verbose_name='Esito Visita')),
                ('report_notes', models.TextField(blank=True, verbose_name='Relazione e Note della Visita')),
            ],
            options={
                'verbose_name': 'Visita Pre-Affido',
                'verbose_name_plural': 'Visite Pre-Affido',
            },
        ),
    ]
