# Generated by Django 5.0.14 on 2026-10-02 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Candidato Adottante'),
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='users.shelterprofile', verbose_name='Rifugio di Appartenenza'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.animal', verbose_name='Animale Richiesto'),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.animal', verbose_name='Animale'),
        ),
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='core.breed', verbose_name='Razza'),
        ),
        migrations.AddField(
            model_name='homevisit',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_visit', to='core.adoptionapplication', verbose_name='Domanda di Adozione'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionapplication',
            unique_together={('adopter', 'animal')},
        ),
    ]
