# Generated by Django 5.0.14 on 2026-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Descrizione e Carattere (Inglese)'),
        ),
    ]
