# Generated by Django 5.0.14 on 2026-10-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='behavior_profile_completed',
            field=models.BooleanField(default=False, verbose_name='Profilo comportamentale completato'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_spayed_neutered',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sterilizzato / Castrato'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='is_vaccinated',
            field=models.BooleanField(blank=True, null=True, verbose_name='Vaccinato'),
        ),
    ]
