# Generated by Django 5.0.14 on 2026-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_animal_behavior_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='special_needs_summary',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sintesi pubblica bisogni speciali'),
        ),
    ]
