# Generated by Django 5.0.14 on 2026-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_animal_special_needs_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='license_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Licenza Immagine'),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='source_page',
            field=models.URLField(blank=True, verbose_name='Fonte Immagine'),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL Immagine Esterna'),
        ),
        migrations.AlterField(
            model_name='animalimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='animals/', verbose_name='File Immagine'),
        ),
    ]
