# Generated by Django 5.0.14 on 2026-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_animalimage_license_label_animalimage_source_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('istat_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codice ISTAT')),
                ('name', models.CharField(max_length=100, verbose_name='Comune')),
                ('province_code', models.CharField(max_length=3, verbose_name='Codice provincia ISTAT')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('province_abbreviation', models.CharField(max_length=2, verbose_name='Sigla provincia')),
                ('region', models.CharField(max_length=100, verbose_name='Regione')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitudine')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitudine')),
                ('postal_codes', models.JSONField(blank=True, default=list, verbose_name='CAP')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'ordering': ['name', 'istat_code'],
            },
        ),
    ]
