# Generated by Django 5.0.14 on 2026-10-02 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(verbose_name='Punteggio Compatibilità Globale (0-100)')),
                ('score_breakdown', models.JSONField(default=dict, help_text='JSON contenente i dettagli per sottocategoria: lifestyle, space, experience, etc.', verbose_name='Scomposizione Punteggio')),
                ('predicted_adoption_time_days', models.FloatField(blank=True, null=True, verbose_name='Tempo Stimato di Adozione (Giorni da Cox Model)')),
                ('survival_probability_30d', models.FloatField(blank=True, null=True, verbose_name='Probabilità Adozione entro 30gg')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Data Calcolo')),
            ],
            options={
                'verbose_name': 'Risultato Matching ML',
                'verbose_name_plural': 'Risultati Matching ML',
            },
        ),
        migrations.CreateModel(
            name='AdoptionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_successful', models.BooleanField(default=True, verbose_name='Adozione Riuscita con Successo')),
                ('satisfaction_rating', models.PositiveIntegerField(default=5, help_text='Valutazione da 1 (molto insoddisfatto) a 5 (eccellente)', verbose_name='Punteggio Soddisfazione')),
                ('return_reason', models.TextField(blank=True, verbose_name='Motivo eventuale rinuncia / restituzione')),
                ('feedback_notes', models.TextField(blank=True, verbose_name="Note dell'Adottante o del Rifugio")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Feedback')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.adoptionapplication', verbose_name='Domanda di Adozione')),
            ],
            options={
                'verbose_name': 'Feedback Adozione (ML Retraining Data)',
                'verbose_name_plural': 'Feedback Adozioni',
            },
        ),
    ]
