# Generated by Django 5.0.14 on 2026-10-02 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to=settings.AUTH_USER_MODEL, verbose_name='Adottante'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='core.animal', verbose_name='Animale'),
        ),
        migrations.AddIndex(
            model_name='matchresult',
            index=models.Index(fields=['adopter', '-overall_score'], name='matching_ma_adopter_0b8ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchresult',
            unique_together={('adopter', 'animal')},
        ),
    ]
