# Generated by Django 5.0.14 on 2026-10-02 08:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADOPTER', 'Adottante'), ('SHELTER', 'Rifugio / Canile'), ('ADMIN', 'Amministratore')], default='ADOPTER', max_length=20, verbose_name='Ruolo')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numero di Telefono')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Indirizzo')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Città')),
                ('province', models.CharField(blank=True, max_length=10, verbose_name='Provincia')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='CAP')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Profilo')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Consenso Privacy GDPR')),
                ('gdpr_consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Consenso GDPR')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Consenso Marketing')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Registrazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data Aggiornamento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdopterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(choices=[('APARTMENT_NO_BALCONY', 'Appartamento senza balcone'), ('APARTMENT_BALCONY', 'Appartamento con balcone/terrazzo'), ('HOUSE_GARDEN', 'Casa indipendente con giardino'), ('VILLA_PARK', 'Villa / Casale con terreno')], default='APARTMENT_BALCONY', max_length=30, verbose_name='Tipologia Abitazione')),
                ('garden_sqm', models.PositiveIntegerField(default=0, verbose_name='Superficie Giardino (mq)')),
                ('family_members_count', models.PositiveIntegerField(default=1, verbose_name='Componenti Nucleo Familiare')),
                ('has_children', models.BooleanField(default=False, verbose_name='Presenza Bambini')),
                ('children_ages_info', models.CharField(blank=True, max_length=200, verbose_name='Età Bambini')),
                ('has_other_pets', models.BooleanField(default=False, verbose_name='Presenza Altri Animali')),
                ('other_pets_details', models.TextField(blank=True, verbose_name='Dettagli Altri Animali in Casa')),
                ('hours_away_from_home', models.PositiveIntegerField(default=4, verbose_name='Ore fuori casa al giorno')),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentario'), ('MODERATE', 'Moderatamente attivo'), ('ACTIVE', 'Molto attivo / Sportivo')], default='MODERATE', max_length=20, verbose_name='Livello Attività Fisica')),
                ('experience_level', models.CharField(choices=[('BEGINNER', 'Prima esperienza'), ('INTERMEDIATE', 'Esperienza intermedia'), ('EXPERT', 'Esperto / Educatore Cinofilo')], default='BEGINNER', max_length=20, verbose_name='Livello Esperienza')),
                ('monthly_budget_approx', models.DecimalField(decimal_places=2, default=100.0, max_digits=8, verbose_name='Budget Mensile Mantenimento (€)')),
                ('preferred_species', models.CharField(default='DOG', max_length=20, verbose_name='Specie Preferita')),
                ('preferred_age_min_months', models.PositiveIntegerField(default=0, verbose_name='Età Minima Preferita (mesi)')),
                ('preferred_age_max_months', models.PositiveIntegerField(default=240, verbose_name='Età Massima Preferita (mesi)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adopter_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Profilo Adottante',
                'verbose_name_plural': 'Profili Adottanti',
            },
        ),
        migrations.CreateModel(
            name='ShelterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=255, verbose_name='Nome Struttura / Rifugio')),
                ('tax_code_vat', models.CharField(max_length=30, verbose_name='Codice Fiscale / Partita IVA')),
                ('official_email', models.EmailField(max_length=254, verbose_name='Email Ufficiale Struttura')),
                ('website_url', models.URLField(blank=True, verbose_name='Sito Web')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione Rifugio')),
                ('capacity_total', models.PositiveIntegerField(default=50, verbose_name='Capienza Totale Ospiti')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Struttura Verificata')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='Data Verifica Approval')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utente Gestore')),
            ],
            options={
                'verbose_name': 'Profilo Rifugio',
                'verbose_name_plural': 'Profili Rifugi',
            },
        ),
    ]
