# Generated by Django 5.0.14 on 2026-10-02 08:42

from django.db import migrations, models


def mark_previously_verified_shelters_approved(apps, schema_editor):
    shelter = apps.get_model('users', 'ShelterProfile')
    shelter.objects.using(schema_editor.connection.alias).filter(is_verified=True).update(
        verification_status='APPROVED'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelterprofile',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ragione Sociale'),
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='organization_type',
            field=models.CharField(choices=[('MUNICIPAL_SHELTER', 'Canile comunale'), ('PRIVATE_SHELTER', 'Canile privato'), ('CATTERY', 'Gattile'), ('ASSOCIATION', 'Associazione'), ('RESCUE', 'Rifugio'), ('OTHER', 'Altro')], default='OTHER', max_length=30, verbose_name='Tipo Struttura'),
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Motivo Rifiuto'),
        ),
        migrations.AddField(
            model_name='shelterprofile',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'In attesa'), ('APPROVED', 'Approvato'), ('REJECTED', 'Rifiutato')], default='PENDING', max_length=10, verbose_name='Stato Verifica'),
        ),
        migrations.RunPython(mark_previously_verified_shelters_approved, migrations.RunPython.noop),
    ]
