# Generated by Django 5.0.14 on 2026-10-02 11:16

import django.db.models.deletion
from django.db.models import Q
from django.db import migrations, models


def backfill_user_comuni(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Comune = apps.get_model('core', 'Comune')
    database = schema_editor.connection.alias
    for user in User.objects.using(database).exclude(city='').iterator():
        matches = Comune.objects.using(database).filter(
            name__iexact=user.city,
        ).filter(
            Q(province_abbreviation__iexact=user.province)
            | Q(province__iexact=user.province)
        ).values_list('pk', flat=True)[:2]
        matches = list(matches)
        if len(matches) == 1:
            User.objects.using(database).filter(pk=user.pk).update(comune_id=matches[0])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comune'),
        ('users', '0002_shelterprofile_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.comune', verbose_name='Comune di riferimento'),
        ),
        migrations.RunPython(backfill_user_comuni, migrations.RunPython.noop),
    ]
