# Generated by Django 5.0.14 on 2026-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDPRConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('TERMS', 'Termini e Condizioni'), ('PRIVACY', 'Informativa Privacy GDPR'), ('MARKETING', 'Comunicazioni Marketing'), ('PROFILING', 'Profilazione e Algoritmi ML')], max_length=20, verbose_name='Tipologia Consenso')),
                ('granted', models.BooleanField(verbose_name='Consenso Accordato')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP (Anonimizzato)')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent Browser')),
                ('privacy_policy_version', models.CharField(default='1.0', max_length=20, verbose_name='Versione Informativa')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Ora Registrazione')),
            ],
            options={
                'verbose_name': 'Registro Consenso GDPR',
                'verbose_name_plural': 'Registro Consensi GDPR',
                'ordering': ['-timestamp'],
            },
        ),
    ]
